
export enum Difficulty {
  EASY = 'Fácil',
  MEDIUM = 'Médio',
  HARD = 'Difícil'
}

export interface Question {
  id: string;
  text: string;
  options: string[];
  correctAnswerIndex: number;
  explanation: string;
}

export interface QuizConfig {
  topic: string;
  difficulty: Difficulty;
  numberOfQuestions: number;
}

export interface StudyMaterial {
  id: string;
  title: string;
  category: string;
  type: 'PDF' | 'VIDEO' | 'ARTICLE';
  duration?: string; // e.g., "15 min" or "10 pages"
  updatedAt: string;
  summary?: string; // Brief description of the content
  content?: string; // The full educational content generated by AI
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
}

export interface NewsItem {
  id: string;
  title: string;
  institution: string;
  date: string;
  status: 'Aberto' | 'Previsto' | 'Encerrado';
}

// New Types for Routine
export interface RoutineTask {
  subject: string;
  activity: string; // "Ler PDF", "Resolver Questões", "Revisão"
  duration: string; // "1h", "30min"
}

export interface DailySchedule {
  day: string; // "Segunda", "Terça"...
  tasks: RoutineTask[];
  focus: string; // Main focus of the day
}

export interface StudyRoutine {
  id?: string;
  targetExam: string;
  hoursPerDay: number;
  weekSchedule: DailySchedule[];
  createdAt: Date;
}
